name: hr
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.3.0
  fl_chart: ^0.71.0
  dropdown_button2: ^2.3.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.5
  numberpicker: ^2.1.2
  file_picker: ^10.3.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  video_player: ^2.10.0
  camera: ^0.11.2
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^11.1.0
  smooth_page_indicator: ^1.2.1
  flutter_card_swiper: ^7.0.2
  path_provider: ^2.0.15
  open_filex: ^4.3.4
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.3.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_native_splash:
  color: "#121212" # background color
  image: assets/images/business_center_splash.png # logo di tengah
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/business_center.png"
  adaptive_icon_background: "#13214B"
  adaptive_icon_foreground: "assets/images/business_center.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/business_center.png"
    background_color: "#13214B"
    theme_color: "#13214B"
  windows:
    generate: true
    image_path: "assets/images/business_center.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/business_center.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
