name: hr
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.3.0
  fl_chart: ^0.71.0
  dropdown_button2: ^2.3.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.5
  numberpicker: ^2.1.2
  file_picker: ^10.3.2
<<<<<<< HEAD
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  video_player: ^2.10.0
  camera: ^0.11.2
=======
  video_player: ^2.6.0
>>>>>>> eabfce30c9e9112c3a4c607264e6eb7db0a5f576

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
